#!/bin/bash
#password:123qweASD_
sudo apt update
sudo apt list --upgradable
sudo apt upgrade
sudo apt install mysql-server
sudo apt-cache mysql-server
sudo systemctl start mysql.service
sudo mysql_secure_installation
printf "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '123qweASD_';\n"
sudo mysql
mysql -u root -p
